- hosts: all

  vars:
    snaps:
      - name: code
        classic: true
      - name: go
        classic: true
      - name: microk8s
        classic: true
      - name: kubectl
        classic: true
      - name: docker
        classic: false
      - name: chromium
        classic: false
  become: yes
  tasks:
    - name: Install snaps
      snap:
        name: "{{ item.name }}"
        state: present
        classic: "{{ item.classic }}"
      with_items: "{{ snaps }}"
