---
- hosts: ubuntu
  gather_facts: yes
  become: yes
  vars:
    packages:
#      - xfce4
#      - xfce4-goodies
      - sddm
      - kubuntu-desktop
      - xorg
      - dbus-x11
      - x11-xserver-utils
      - xrdp
      - firefox

    base_packages:
      - bash
      - ansible
      - vim

    snaps:
      - chromium
      - postman

    classic_snaps:
      - code
      - slack
      - dbeaver-ce
      - kubectl

    username: ubuntu
    password: "Pass@Word1"

  tasks:
    - name: Update apt
      apt:
        update_cache: yes
        upgrade: full
        state: latest

    - name: Install xfce4
      apt:
        name: "{{ packages }}"
        state: present

    - name: Add xrdp user to ssl-cert group
      user:
        name: xrdp
        groups: ssl-cert
        append: true
        state: present

    - name: Add password for ubuntu user
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512', 'saltedsecret') }}"

    - name: Ensure xrdp is started
      service:
        name: xrdp
        state: started

    - name: Install snaps
      snap:
        name: "{{ snaps }}"
        state: present

    - name: Install classic contained snaps
      snap: 
        name: "{{ classic_snaps }}"
        classic: yes
        state: present



